### ISSUE TITLE
await / async

### ISSUE THREAD

**Issue by electic** [jaz303/git-clone#6]
Hi,

Great simple component. Love it. Question though, this does not seem to work with await?

**Comment by picheli20** [comment]
Have just created a PR for it

**Comment by jaz303** [comment]
I know the referenced #9 added this functionality to the original function but I don't like APIs that change their fundamental behaviour/concurrency model based on arguments, so I've added promise support via an alternate import (so as to avoid breaking backwards compatibility)

```javascript
const gitClone = require('git-clone/promise');
```

Still to write tests then I'll push v0.2.0. Assuming there are no issues with this, I'll make promises the default API in 1.0.0 since by now it's safe to say they're the favoured approach.
